using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AlgoritmPrizm.BLL
{
    public class JsonPrintFiscDocTender
    {
        public string link;
        public string sid;
        public string created_by;
        public DateTime created_datetime;
        public string modified_by;
        public DateTime? modified_datetime;
        public DateTime post_date;
        public int tender_type;
        public int tender_pos;
        public double amount;
        public double taken;
        public double given;
        public bool matched;
        public string eft_res_tender_state;
        public string manual_name;
        public string manual_remark;
        public string currency_sid;
        public string currency_name;
        public string tender_name;
        public string alphabetic_code;
        public string tender_sid;
        public string check_type;
        public string check_number;
        public string company;
        public string first_name;
        public string last_name;
        public string work_phone;
        public string home_phone;
        public string state;
        public string drivers_license;
        public string drivers_license_expiration;
        public DateTime? date_of_birth;
        public string authorization_code;
        public string eft_transaction_id;
        public string avs_response_code;
        public string failure_message;
        public string eftdata1;
        public string eftdata2;
        public string eftdata3;
        public string eftdata4;
        public string eftdata5;
        public string eftdata6;
        public string eftdata7;
        public string eftdata8;
        public string eftdata9;
        public string eftdata0;
        public string entry_method;
        public string eftdata10;
        public string eftdata11;
        public string eftdata12;
        public string eftdata13;
        public string eftdata14;
        public string eftdata15;
        public string eftdata16;
        public string eftdata17;
        public string eftdata18;
        public string eftdata19;
        public string eftdatabsmer;
        public string eftdatabscust;
        public string card_number;
        public string card_type_sid;
        public string card_holder_name;
        public string card_expiration_month;
        public string card_expiration_year;
        public string is_normal_sale;
        public string is_present;
        public string card_postal_code;
        public string l2_result_code;
        public string card_type_name;
        public string emv_ai_applabel;
        public string emv_ai_aid;
        public string emv_ci_cardexpirydate;
        public string emv_crypto_cryptogramtype;
        public string emv_crypto_cryptogram;
        public string emv_pinstatement;
        public string charge_net_days;
        public string charge_discount_days;
        public string charge_discount_percent;
        public string base_taken;
        public string base_given;
        public string give_rate;
        public string take_rate;
        public string foreign_currency_sid;
        public string foreign_currency_name;
        public string foreign_alphabetic_code;
        public string trace_number;
        public string internal_reference_number;
        public string balance;
        public string certificate_number;
        public DateTime? payment_date;
        public string payment_remark;
        public string central_payment_id;
        public string central_credit_balance;
        public string central_commit_state;
        public string redeem_credit_id_10;
        public string new_credit_id_10;
        public string new_credit_value;
        public string new_credit_id;
        public string redeem_credit_id;
        public string central_activation_id;
        public string central_card_number;
    }
}
